definitions:
  EffectiveMobile.Song:
    properties:
      group:
        type: string
      id:
        type: integer
      link:
        type: string
      release_date:
        type: string
      song_name:
        type: string
      text:
        type: string
    type: object
info:
  contact: {}
paths:
  /info:
    delete:
      consumes:
      - application/json
      description: Удаление песни по предоставленным данным
      parameters:
      - description: Данные песни для удаления. Передайте либо ID, либо название и
          группу песни
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/EffectiveMobile.Song'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Удаление песни
      tags:
      - songs
    get:
      consumes:
      - application/json
      description: Получение списка песен из базы данных
      parameters:
      - description: Название песни
        in: query
        name: song
        required: true
        type: string
      - description: Группа
        in: query
        name: group
        required: true
        type: string
      - description: ID песни
        in: query
        name: id
        type: integer
      - description: Номер страницы
        in: query
        name: page
        type: integer
      - description: Дата с
        in: query
        name: since
        type: string
      - description: Дата по
        in: query
        name: to
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Получение списка песен
      tags:
      - songs
    post:
      consumes:
      - application/json
      description: Добавление новой песни в базу данных
      parameters:
      - description: Данные песни
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/EffectiveMobile.Song'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Добавление новой песни
      tags:
      - songs
    put:
      consumes:
      - application/json
      description: Обновление информации о песне по предоставленным данным
      parameters:
      - description: Данные песни для обновления
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/EffectiveMobile.Song'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Обновление информации о песне
      tags:
      - songs
  /info/verse:
    get:
      consumes:
      - application/json
      description: Получение текста конкретного куплета песни.
      parameters:
      - description: Название песни
        in: query
        name: song
        type: string
      - description: Группа
        in: query
        name: group
        type: string
      - description: ID песни
        in: query
        name: id
        type: integer
      - description: Номер куплета. Передайте с ним либо ID, либо название и группу
          песни
        in: query
        name: verse
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Получение текста песни
      tags:
      - songs
swagger: "2.0"
